season: 2025 - 2026
periods:
  - name: veld
    text: Van vrijdag 1 augustus 2025 tot en met zondag 26 oktober 2025, van maandag 16 maart 2026 tot en met vrijdag 29 mei 2026.
    teams:
      - name: U5
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: grotebaan
      - name: U7
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: grotebaan
      - name: U9
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:00"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:00"
            location: grotebaan
      - name: U11
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
      - name: U13
        trainings:
          - weekday: woensdag
            starts_at: "18:30"
            ends_at: "20:00"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:30"
            location: grotebaan
      - name: U15
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
      - name: U17
        trainings:
          - weekday: woensdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
      - name: U19
        trainings:
          - weekday: woensdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
      - name: Senioren
        trainings:
          - weekday: woensdag
            starts_at: "20:45"
            ends_at: "22:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "20:45"
            ends_at: "22:15"
            location: grotebaan
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:30"
            ends_at: "22:00"
            location: grotebaan
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:30"
            ends_at: "20:30"
            location: grotebaan
  - name: zaal
    text: Van maandag 27 oktober 2025 tot en met zondag 15 maart 2026.
    teams:
      - name: U5
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: klimroos
      - name: U7
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: sjib
      - name: U9
        trainings:
          - weekday: woensdag
            starts_at: "17:00"
            ends_at: "18:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: sjib
      - name: U11
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
      - name: U13
        trainings:
          - weekday: woensdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
      - name: U15
        trainings:
          - weekday: dinsdag
            starts_at: "17:30"
            ends_at: "19:15"
            location: zand
          - weekday: donderdag
            starts_at: "17:30"
            ends_at: "19:00"
            location: zand
      - name: U17
        trainings:
          - weekday: dinsdag
            starts_at: "19:15"
            ends_at: "21:00"
            location: zand
          - weekday: donderdag
            starts_at: "17:30"
            ends_at: "19:00"
            location: zand
      - name: U19
        trainings:
          - weekday: dinsdag
            starts_at: "19:15"
            ends_at: "21:00"
            location: zand
          - weekday: donderdag
            starts_at: "17:30"
            ends_at: "19:00"
            location: zand
      - name: Senioren
        trainings:
          - weekday: dinsdag
            starts_at: "20:45"
            ends_at: "22:15"
            location: tbd
          - weekday: donderdag (oneven weken)
            starts_at: "21:00"
            ends_at: "23:00"
            location: zand
          - weekday: vrijdag (even weken)
            starts_at: "20:30"
            ends_at: "22:30"
            location: zand
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "22:00"
            location: mixx
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: mixx
