season: 2024 - 2025
periods:
  - name: veld
    text: Van maandag 29 juli 2024 tot en met zondag 27 oktober 2024, van maandag 3 maart 2025 tot en met vrijdag 30 mei 2025.
    teams:
      - name: U5
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: grotebaan
      - name: U7
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: grotebaan
      - name: U9
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:00"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:00"
            location: grotebaan
      - name: U11
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
      - name: U13
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
      - name: U15
        trainings:
          - weekday: woensdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: grotebaan
      - name: U17
        trainings:
          - weekday: woensdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
      - name: U19
        trainings:
          - weekday: woensdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: grotebaan
      - name: Senioren
        trainings:
          - weekday: woensdag
            starts_at: "20:45"
            ends_at: "22:15"
            location: grotebaan
          - weekday: vrijdag
            starts_at: "20:45"
            ends_at: "22:15"
            location: grotebaan
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:30"
            ends_at: "22:00"
            location: grotebaan
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:30"
            ends_at: "20:30"
            location: grotebaan
  - name: zaal
    text: Van maandag 28 oktober 2024 tot en met zondag 2 maart 2025.
    teams:
      - name: U5
        trainings:
          - weekday: vrijdag
            starts_at: "17:45"
            ends_at: "18:45"
            location: klimroos
      - name: U7
        trainings:
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: sjib
      - name: U9
        trainings:
          - weekday: woensdag
            starts_at: "17:00"
            ends_at: "18:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: sjib
      - name: U11
        trainings:
          - weekday: woensdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
      - name: U13
        trainings:
          - weekday: woensdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: tumkens
          - weekday: vrijdag
            starts_at: "18:00"
            ends_at: "19:00"
            location: tumkens
      - name: U15
        trainings:
          - weekday: dinsdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: sitea
          - weekday: donderdag
            starts_at: "17:45"
            ends_at: "19:15"
            location: sitea
      - name: U17
        trainings:
          - weekday: dinsdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: sitea
          - weekday: donderdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: sitea
      - name: U19
        trainings:
          - weekday: dinsdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: sitea
          - weekday: donderdag
            starts_at: "19:15"
            ends_at: "20:45"
            location: sitea
      - name: Senioren
        trainings:
          - weekday: dinsdag
            starts_at: "20:45"
            ends_at: "22:15"
            location: sitea
          - weekday: vrijdag
            starts_at: "21:00"
            ends_at: "23:00"
            location: mixx
      - name: Gewestelijken
        trainings:
          - weekday: vrijdag
            starts_at: "20:00"
            ends_at: "22:00"
            location: mixx
      - name: Recreanten
        trainings:
          - weekday: vrijdag
            starts_at: "19:00"
            ends_at: "20:00"
            location: mixx
